FROM rockylinux:9

WORKDIR ENTRYPOINT TODO

# Path to Arras Release
RUN export PATH=${}/bin:${PATH}

# Path to RDL2DSO
RUN export RDSL2_DSO_PATH=${}/rdl2dso:${}/rdl2dso.proxy

# Required to be overridden by Kubernetes
CMD ["sleep", "36000"]