apiVersion: apps/v1
kind: Deployment
metadata:
  name: arras-coordinator
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.coordinator.replicas }}
  selector:
    matchLabels:
      role: arras-coordinator
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: arras-coordinator
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: coordinator
        image: {{ .Values.coordinator.image }}
        ports:
        - containerPort: 8888
        resources:
{{ toYaml .Values.coordinator.resources | indent 10 }}