apiVersion: v1
kind: Service
metadata:
  name: arras-coordinator
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: ClusterIP
  selector:
    role: arras-coordinator
    release: {{ .Release.Name }}
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP