apiVersion: apps/v1
kind: Deployment
metadata:
  name: arras-node
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.node.replicas }}
  selector:
    matchLabels:
      role: arras-node
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: arras-node
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: node
        image: {{ .Values.node.image }}
        command:
        - arras4_node
        - --coordinator-host
        - arras-coordinator
        - --coordinator-port
        - 8888
        - -l
        - "{{ .Values.node.logLevel }}"
        - --no-consul
        resources:
{{ toYaml .Values.node.resources | indent 10 }}