apiVersion: v1
kind: Service
metadata:
  name: {{ include "moonray-arras.fullname" . }}-coordinator
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: arras-coordinator
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.coordinator.port }}
    targetPort: {{ .Values.coordinator.port }}
    protocol: TCP