namespace: moonray

coordinator:
  image: whyspur/coordv1:latest
  replicas: 1
  port: 8888
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"

node:
  image: your-registry/arras-node:latest
  replicas: 3
  resources:
    requests:
      memory: "8Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "1"
  # Additional node configuration
  logLevel: 5
  noConsul: true
